#!/usr/bin/bash
#wget Mirror List
curl -O https://raw.githubusercontent.com/benasanders/ArchMBPScripts/master/mirrorlist
mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
cp mirrorlist /etc/pacman.d/mirrorlist
#Set time and format/mount drive
timedatectl set-ntp true
mkfs.ext4 /dev/sda4
e2label /dev/sda4 Arch
mount /dev/sda4 /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
#Install the OS
pacstrap /mnt base base-devel
genfstab -L /mnt >> /mnt/etc/fstab
echo "edit fstab to"
echo "discard,rw,noatime,data=writeback"
echo "Then change root and continue to 2"
echo "arch-chroot /mnt"
